<?php
 return array (
  'db_engine' => 'MyISAM',
  'site_name' => 'opal系统',
  'description' => 'opal系统-专注于开源系统的开发',
  'allowed_upload_imgs_type' => 'jpeg,bmp,gif,png,jpg,ico',
  'up_type' => 'oss',
  'keywords' => 'opal系统-专注于开源系统的开发',
  'up_maxSize' => '0',
  'sensitive_words' => '',
  'def_focus_uids' => '1',
  'answer_edit_time' => '30',
  'cache_level_high' => '60',
  'cache_level_normal' => '600',
  'cache_level_low' => '1800',
  'unread_flush_interval' => '100',
  'newer_invitation_num' => '5',
  'index_per_page' => '20',
  'from_email' => '502443279@qq.com',
  'img_url' => '',
  'upload_url' => 'http://cooldreamer.org/ask/uploads',
  'upload_dir' => '/selfproject/5ihelp/ask/uploads',
  'ui_style' => '',
  'uninterested_fold' => '5',
  'sina_akey' => '3453155715',
  'sina_skey' => 'a09ddb87450a2d65337c8334dd99b810',
  'sina_weibo_enabled' => 'N',
  'answer_unique' => 'N',
  'notifications_per_page' => '10',
  'contents_per_page' => 
  array (
    0 => '30',
    1 => '30',
  ),
  'hot_question_period' => '7',
  'category_display_mode' => 'list',
  'recommend_users_number' => '6',
  'ucenter_enabled' => 'N',
  'register_valid_type' => 'email',
  'best_answer_day' => '30',
  'answer_self_question' => 'Y',
  'censoruser' => 'admin,jerry,管理员,5ihelp,关键字,php,thinkask,ucenter,reg,logo,login,江泽民，习近平，毛泽东，11111，ssss,aaaaa,wwwww,ffff',
  'best_answer_min_count' => '3',
  'reputation_function' => '[最佳答案]*3+[赞同]*1-[反对]*1+[发起者赞同]*2-[发起者反对]*1',
  'db_version' => '20160523',
  'statistic_code' => '<div style=\'display:none\'>
<script src="https://s19.cnzz.com/z_stat.php?id=1268647169&web_id=1268647169" language="JavaScript"></script>

</div>',
  'cdn_domain' => 'https://cdn.jerryblog.cn',
  'web_version' => 'v3.5',
  'soft_domain' => 'https://soft.jerryblog.cn',
  'activemq_url' => '47.98.194.93',
  'activemq_port' => '61613',
  'upload_enable' => 'Y',
  'answer_length_lower' => '2',
  'quick_publish' => 'Y',
  'register_type' => 'open',
  'question_title_limit' => '100',
  'register_seccode' => 'N',
  'admin_login_seccode' => 'Y',
  'comment_limit' => '0',
  'backup_dir' => '',
  'best_answer_reput' => '20',
  'publisher_reputation_factor' => '10',
  'request_route_custom' => '',
  'upload_size_limit' => '512',
  'upload_avatar_size_limit' => '512',
  'topic_title_limit' => '12',
  'url_rewrite_enable' => 'N',
  'best_agree_min_count' => '3',
  'site_close' => 'N',
  'close_notice' => '站点已关闭，管理员请登录。',
  'qq_login_enabled' => 'Y',
  'qq_login_app_id' => '101388938',
  'qq_login_app_key' => '177bf26979d4a434e950f7cc916aa0f4',
  'integral_system_enabled' => 'N',
  'integral_system_config_register' => '2000',
  'integral_system_config_profile' => '100',
  'integral_system_config_invite' => '200',
  'integral_system_config_best_answer' => '200',
  'integral_system_config_answer_fold' => '-50',
  'integral_system_config_new_question' => '-20',
  'integral_system_config_new_answer' => '-5',
  'integral_system_config_thanks' => '-10',
  'integral_system_config_invite_answer' => '-10',
  'username_rule' => '1',
  'username_length_min' => '5',
  'username_length_max' => '10',
  'category_enable' => 'Y',
  'integral_unit' => '金币',
  'nav_menu_show_child' => 'N',
  'anonymous_enable' => 'Y',
  'report_reason' => '',
  'allowed_upload_types' => 'xml,xls,doc,zip,rar,text,ico,json',
  'site_announce' => '',
  'alipay_seller_id' => '',
  'icp_beian' => '',
  'report_message_uid' => '1',
  'today_topics' => '',
  'welcome_recommend_users' => '',
  'welcome_message_pm' => '尊敬的{username}，您已经注册成为{sitename}的会员，请您在发表言论时，遵守当地法律法规。
如果您有什么疑问可以联系管理员。
{sitename}',
  'time_style' => 'Y',
  'reputation_log_factor' => '3',
  'advanced_editor_enable' => 'Y',
  'auto_question_lock_day' => '0',
  'default_timezone' => 'Etc/GMT-8',
  'reader_questions_last_days' => '30',
  'reader_questions_agree_count' => false,
  'weixin_mp_token' => '',
  'new_user_email_setting' => 
  array (
    0 => 'FOLLOW_ME',
    1 => 'QUESTION_INVITE',
    2 => 'NEW_ANSWER',
    3 => 'NEW_MESSAGE',
    4 => 'QUESTION_MOD',
  ),
  'new_user_notification_setting' => 
  array (
  ),
  'user_action_history_fresh_upgrade' => 'Y',
  'cache_dir' => '',
  'ucenter_charset' => 'UTF-8',
  'question_topics_limit' => '10',
  'mail_config' => 
  array (
    'Host' => 'smtp.126.com',
    'port' => '25',
    'username' => '15220138389@126.com',
    'password' => 'Cyl502443279',
    'from_email' => 'thinkask@thinkask.cn',
    'testmail' => '502443279@qq.com',
  ),
  'auto_create_social_topics' => 'N',
  'weixin_subscribe_message_key' => '',
  'weixin_no_result_message_key' => '',
  'weixin_mp_menu' => 
  array (
  ),
  'new_question_force_add_topic' => 'N',
  'unfold_question_comments' => 'N',
  'report_diagnostics' => 'Y',
  'weixin_app_id' => '',
  'weixin_app_secret' => '',
  'weixin_account_role' => 'base',
  'weibo_msg_enabled' => 'N',
  'weibo_msg_published_user' => false,
  'admin_notifications' => 
  array (
    'answer_approval' => 0,
    'question_approval' => 0,
    'article_approval' => 0,
    'article_comment_approval' => 0,
    'unverified_modify_count' => 0,
    'user_report' => 0,
    'register_approval' => 0,
    'verify_approval' => 0,
    'last_version' => 
    array (
      'version' => '3.1.9',
      'build_day' => '20160523',
    ),
    'sina_users' => NULL,
    'receive_email_error' => NULL,
  ),
  'slave_mail_config' => '',
  'receiving_email_global_config' => 
  array (
    'enabled' => 'N',
    'publish_user' => NULL,
  ),
  'last_sent_valid_email_id' => 0,
  'google_login_enabled' => 'N',
  'google_client_id' => '',
  'google_client_secret' => '',
  'facebook_login_enabled' => 'N',
  'facebook_app_id' => '',
  'facebook_app_secret' => '',
  'twitter_login_enabled' => 'N',
  'twitter_consumer_key' => '',
  'twitter_consumer_secret' => '',
  'weixin_encoding_aes_key' => '',
  'integral_system_config_answer_change_source' => 'Y',
  'enable_help_center' => 'N',
  'ucenter_path' => '',
  'register_agreement' => '当您申请用户时，表示您已经同意遵守本规章。
欢迎您加入本站点参与交流和讨论，本站点为社区，为维护网上公共秩序和社会稳定，请您自觉遵守以下条款：

一、不得利用本站危害国家安全、泄露国家秘密，不得侵犯国家社会集体的和公民的合法权益，不得利用本站制作、复制和传播下列信息：
　（一）煽动抗拒、破坏宪法和法律、行政法规实施的；
　（二）煽动颠覆国家政权，推翻社会主义制度的；
　（三）煽动分裂国家、破坏国家统一的；
　（四）煽动民族仇恨、民族歧视，破坏民族团结的；
　（五）捏造或者歪曲事实，散布谣言，扰乱社会秩序的；
　（六）宣扬封建迷信、淫秽、色情、赌博、暴力、凶杀、恐怖、教唆犯罪的；
　（七）公然侮辱他人或者捏造事实诽谤他人的，或者进行其他恶意攻击的；
　（八）损害国家机关信誉的；
　（九）其他违反宪法和法律行政法规的；
　（十）进行商业广告行为的。

二、互相尊重，对自己的言论和行为负责。
三、禁止在申请用户时使用相关本站的词汇，或是带有侮辱、毁谤、造谣类的或是有其含义的各种语言进行注册用户，否则我们会将其删除。
四、禁止以任何方式对本站进行各种破坏行为。
五、如果您有违反国家相关法律法规的行为，本站概不负责，您的登录信息均被记录无疑，必要时，我们会向相关的国家管理部门提供此类信息。',
  'contents_per_article' => '20',
  'contents_per_question' => '20',
  'alipay_seller_email' => '',
  'alipay_partner' => '2088202869590751',
  'alipay_key' => '',
  'system_logo' => '4067',
  'open_accusation' => 'Y',
  'open_comment' => 'Y',
  'open_thanks' => 'Y',
  'open_good' => 'Y',
  'accusation_hidden' => '30',
  'must_category' => 'Y',
  'ni_title' => '',
  'nic_id' => '',
  'ni_module' => '',
  'ni_controller' => '',
  'ni_action' => '',
  'ni_url' => '',
  'ni_sort' => '0',
  'ni_target' => '',
  'access_key' => 'OMGujYI3x6ErX5n3',
  'key_secret' => 'pMa79CA7pugE8Eqyo68hKOWxTzQUcs',
  'bucket' => 'datebasejerry',
  'bucket_dir' => '',
  'oss_access_key' => 'OMGujYI3x6ErX5n3',
  'oss_key_secret' => 'pMa79CA7pugE8Eqyo68hKOWxTzQUcs',
  'oss_bucket' => 'datebasejerry',
  'oss_endpoint' => 'oss-cn-shenzhen.aliyuncs.com',
  'oss_bucketssss' => 'datebasejerry',
  'oss_domain' => 'https://imgs.jerryblog.cn',
  'admin_per_all' => '30',
  'system_message_mail' => '502443279@qq.com',
  'login_success' => 'N',
  'reg_success' => 'Y',
  'membership_fees' => '120',
  'membership_picture' => '4063',
  'membership_fees_des' => '<p style="margin-top: 0px; margin-bottom: 0px; padding: 0px; list-style: none; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 12px; white-space: normal; background-color: rgb(255, 255, 255);">&nbsp;&nbsp; 根据第一次理事会会议讨论通过，协会正式注册之后,这些款项将自动转为会员会费，目前所缴会费每年按120元计，已缴纳的会员年限不受今后会费标准变动的影响。此外，会员证的发放、会员权利的享受均以会员会费是否缴纳为依据。欢迎各位群友加入到鹏博爱心互助协会大家庭，履行会员必须的基本义务，享受章程付予会员的基本权利。<br/></p><p><br/></p>',
  'membership_name' => '会费',
  'copy_right' => 'opal开发团队 版权所有',
  'gy_system_logo' => '4061',
  'gy_site_name' => '公益管理系统',
  'gy_description' => '公益管理系统',
  'gy_keywords' => '公益管理系统',
  'gy_copy_right' => 'Copyright ©深圳市鹏博爱心互助协会 服务支持:智元（深圳）科技网络有限公司  design by Jerry',
  'gy_icp_beian' => '粤ICP备16102932号-1',
  'gy_statistic_code' => '',
  'gy_token' => 'Y1Z1331jpO5uzB51',
  'gy_encodingaeskey' => 'M8XL9aa93CNL9ZsczpX9Lx8GZVlsTftDCaJxTGlxdxd',
  'gy_appid' => 'wx32903cf53be41e9a',
  'gy_appsecret' => 'd6987d65941e48f84206787be4bd35b5',
  'sfss' => '',
  'open_cdn' => 'Y',
  'setting1' => false,
  'setting2' => false,
  'token' => 'bJfXrnQlgtyUL6j/eWCqTA==',
  'upimg-input-wx_reply' => '',
  'wx_AppId' => 'sfdsaf',
  'wx_AppSecret' => '',
  'wx_mchid' => '',
  'wx_paysignkey' => '',
  'wx_apiclient_cert' => '',
  'wx_apiclient_key' => '',
);